import React, { useRef, useState } from 'react';
import { FileDown, Image, ChevronDown, ChevronUp } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import toast from 'react-hot-toast';

interface NoteCardProps {
  id: string;
  writerName: string;
  writerPhotoURL?: string;
  writerUniversity: string;
  content: string;
  createdAt: Date;
  showExport?: boolean;
}

const NoteCard: React.FC<NoteCardProps> = ({
  id,
  writerName,
  writerPhotoURL,
  writerUniversity,
  content,
  createdAt,
  showExport = true,
}) => {
  const [expanded, setExpanded] = useState(false);
  const photoCardRef = useRef<HTMLDivElement>(null);

  const dateStr = createdAt.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const handleDownloadPDF = () => {
    toast.promise(
      (async () => {
        const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const pageW = pdf.internal.pageSize.getWidth();
        const pageH = pdf.internal.pageSize.getHeight();
        const margin = 22;
        const contentW = pageW - margin * 2;

        // Amber header band
        pdf.setFillColor(251, 191, 36);
        pdf.roundedRect(0, 0, pageW, 36, 0, 0, 'F');

        // Logo text in header
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Erasmus Memory Capsule', margin, 22);
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'normal');
        pdf.text('A Private Memory Note', pageW - margin, 22, { align: 'right' });

        // Sender block
        pdf.setTextColor(30, 41, 59);
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text('From', margin, 50);
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(14);
        pdf.text(writerName, margin, 59);
        pdf.setFontSize(10);
        pdf.setTextColor(100, 116, 139);
        pdf.text(writerUniversity, margin, 67);
        pdf.text(dateStr, margin, 74);

        // Amber divider
        pdf.setDrawColor(251, 191, 36);
        pdf.setLineWidth(0.8);
        pdf.line(margin, 80, pageW - margin, 80);

        // Note content
        pdf.setTextColor(30, 41, 59);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        pdf.setLineHeightFactor(1.6);
        const lines = pdf.splitTextToSize(content, contentW);
        let y = 91;
        for (const line of lines) {
          if (y > pageH - 25) {
            pdf.addPage();
            y = margin;
          }
          pdf.text(line, margin, y);
          y += 7;
        }

        // Footer
        pdf.setFontSize(8);
        pdf.setTextColor(148, 163, 184);
        pdf.text('Generated by Erasmus Memory Capsule · erasmusmemorycapsule.com', margin, pageH - 12);

        pdf.save(`memory-note-from-${writerName.replace(/\s+/g, '-').toLowerCase()}.pdf`);
      })(),
      {
        loading: 'Generating PDF...',
        success: 'PDF downloaded!',
        error: 'Failed to generate PDF',
      }
    );
  };

  const handleDownloadPhoto = () => {
    toast.promise(
      (async () => {
        if (!photoCardRef.current) throw new Error('Card not found');
        const canvas = await html2canvas(photoCardRef.current, {
          scale: 2.5,
          useCORS: true,
          allowTaint: true,
          backgroundColor: null,
          logging: false,
        });
        const link = document.createElement('a');
        link.download = `memory-card-from-${writerName.replace(/\s+/g, '-').toLowerCase()}.png`;
        link.href = canvas.toDataURL('image/png', 1.0);
        link.click();
      })(),
      {
        loading: 'Creating photo card...',
        success: 'Photo card downloaded!',
        error: 'Failed to create photo card',
      }
    );
  };

  const preview = content.length > 220 ? content.slice(0, 220) + '…' : content;

  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-amber-100 dark:border-slate-700 overflow-hidden">
      <div className="p-5">
        <div className="flex items-start gap-3 mb-3">
          {writerPhotoURL ? (
            <img
              src={writerPhotoURL}
              alt={writerName}
              className="w-12 h-12 rounded-full object-cover flex-shrink-0"
              crossOrigin="anonymous"
              referrerPolicy="no-referrer"
              onError={(e) => { e.currentTarget.style.display = 'none'; }}
            />
          ) : (
            <div className="w-12 h-12 rounded-full bg-amber-200 dark:bg-slate-600 flex items-center justify-center text-lg font-bold text-amber-700 dark:text-amber-300 flex-shrink-0">
              {writerName[0]}
            </div>
          )}
          <div className="flex-1 min-w-0">
            <p className="font-semibold text-slate-800 dark:text-white">{writerName}</p>
            {writerUniversity && (
              <p className="text-xs text-slate-500 dark:text-slate-400">{writerUniversity}</p>
            )}
            <p className="text-xs text-amber-600 dark:text-amber-400 mt-0.5">{dateStr}</p>
          </div>
          <span className="text-xs text-slate-300 dark:text-slate-600 px-2 py-0.5 rounded-full border border-slate-200 dark:border-slate-700 flex items-center gap-1">
            🔒 Private
          </span>
        </div>

        <div className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
          <p className="whitespace-pre-wrap">{expanded ? content : preview}</p>
          {content.length > 220 && (
            <button
              onClick={() => setExpanded(!expanded)}
              className="flex items-center gap-1 mt-2 text-amber-600 dark:text-amber-400 hover:underline text-xs font-medium"
            >
              {expanded ? <><ChevronUp size={14} /> Show less</> : <><ChevronDown size={14} /> Read more</>}
            </button>
          )}
        </div>

        {showExport && (
          <div className="flex gap-2 mt-4">
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-amber-200 dark:border-slate-600 text-amber-700 dark:text-amber-300 hover:bg-amber-50 dark:hover:bg-slate-700 text-xs font-medium transition-colors"
            >
              <FileDown size={13} />
              Download PDF
            </button>
            <button
              onClick={handleDownloadPhoto}
              className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-amber-200 dark:border-slate-600 text-amber-700 dark:text-amber-300 hover:bg-amber-50 dark:hover:bg-slate-700 text-xs font-medium transition-colors"
            >
              <Image size={13} />
              Photo Card
            </button>
          </div>
        )}
      </div>

      {/* Hidden high-quality photo card rendered off-screen for html2canvas */}
      <div
        aria-hidden="true"
        style={{ position: 'fixed', left: '-9999px', top: '-9999px', pointerEvents: 'none' }}
      >
        <div
          ref={photoCardRef}
          style={{
            width: 680,
            background: 'linear-gradient(145deg, #1e293b 0%, #0f172a 50%, #1e3a5f 100%)',
            borderRadius: 28,
            padding: '44px 48px',
            fontFamily: "'Georgia', 'Times New Roman', serif",
            boxSizing: 'border-box',
          }}
        >
          {/* Header row */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 32 }}>
            <div>
              <p style={{ fontSize: 11, color: '#94a3b8', margin: 0, textTransform: 'uppercase', letterSpacing: 2, fontFamily: 'Arial, sans-serif' }}>
                Erasmus Memory Capsule
              </p>
              <p style={{ fontSize: 22, fontWeight: 'bold', color: '#fff', margin: '6px 0 0', fontFamily: 'Arial, sans-serif' }}>
                A Personal Note
              </p>
            </div>
            <div style={{ width: 52, height: 52, borderRadius: '50%', background: 'rgba(251,191,36,0.15)', border: '1px solid rgba(251,191,36,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24, flexShrink: 0 }}>
              ✉️
            </div>
          </div>

          {/* Sender */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 28, padding: '16px 20px', background: 'rgba(255,255,255,0.06)', borderRadius: 16 }}>
            <div style={{ width: 44, height: 44, borderRadius: '50%', background: '#f59e0b', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, fontWeight: 'bold', color: '#fff', flexShrink: 0, fontFamily: 'Arial, sans-serif' }}>
              {writerName[0]}
            </div>
            <div>
              <p style={{ fontSize: 16, fontWeight: 'bold', color: '#fff', margin: 0, fontFamily: 'Arial, sans-serif' }}>{writerName}</p>
              {writerUniversity && <p style={{ fontSize: 12, color: '#94a3b8', margin: '3px 0 0', fontFamily: 'Arial, sans-serif' }}>{writerUniversity}</p>}
              <p style={{ fontSize: 12, color: '#f59e0b', margin: '2px 0 0', fontFamily: 'Arial, sans-serif' }}>{dateStr}</p>
            </div>
          </div>

          {/* Amber divider */}
          <div style={{ height: 1, background: 'linear-gradient(90deg, #f59e0b, transparent)', marginBottom: 28 }} />

          {/* Message */}
          <div style={{ background: 'rgba(255,255,255,0.04)', borderRadius: 16, padding: '24px 28px', border: '1px solid rgba(255,255,255,0.08)' }}>
            <p style={{ fontSize: 15, color: '#e2e8f0', lineHeight: 1.85, margin: 0, whiteSpace: 'pre-wrap', fontStyle: 'italic' }}>
              &ldquo;{content.length > 500 ? content.slice(0, 500) + '…' : content}&rdquo;
            </p>
          </div>

          {/* Footer */}
          <p style={{ fontSize: 10, color: '#475569', margin: '24px 0 0', textAlign: 'center', fontFamily: 'Arial, sans-serif', letterSpacing: 1 }}>
            ERASMUS MEMORY CAPSULE · PRIVATE NOTE
          </p>
        </div>
      </div>
    </div>
  );
};

export default NoteCard;
