import React, { useRef, useState } from 'react';
import { FileDown, Image, ChevronDown, ChevronUp } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import toast from 'react-hot-toast';

interface NoteCardProps {
  id: string;
  writerName: string;
  writerPhotoURL?: string;
  writerUniversity: string;
  content: string;
  createdAt: Date;
}

const NoteCard: React.FC<NoteCardProps> = ({
  id,
  writerName,
  writerPhotoURL,
  writerUniversity,
  content,
  createdAt,
}) => {
  const [expanded, setExpanded] = useState(false);
  const photoCardRef = useRef<HTMLDivElement>(null);

  const dateStr = createdAt.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const handleDownloadPDF = () => {
    toast.promise(
      (async () => {
        const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const pageW = pdf.internal.pageSize.getWidth();
        const margin = 20;
        const contentW = pageW - margin * 2;

        // Header
        pdf.setFillColor(251, 191, 36); // amber-400
        pdf.rect(0, 0, pageW, 30, 'F');
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(18);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Memory Capsule ✈️', margin, 20);

        // Subheader
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        pdf.text('Erasmus Memory Note', pageW - margin, 20, { align: 'right' });

        // Sender info
        pdf.setTextColor(30, 41, 59); // slate-800
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text('From:', margin, 45);
        pdf.setFont('helvetica', 'normal');
        pdf.text(writerName, margin + 15, 45);

        pdf.setFontSize(10);
        pdf.setTextColor(100, 116, 139); // slate-500
        pdf.text(writerUniversity, margin + 15, 52);
        pdf.text(dateStr, margin + 15, 59);

        // Divider
        pdf.setDrawColor(251, 191, 36);
        pdf.setLineWidth(0.5);
        pdf.line(margin, 65, pageW - margin, 65);

        // Content
        pdf.setTextColor(30, 41, 59);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        const lines = pdf.splitTextToSize(content, contentW);
        pdf.text(lines, margin, 75);

        // Footer
        const pageH = pdf.internal.pageSize.getHeight();
        pdf.setTextColor(148, 163, 184);
        pdf.setFontSize(8);
        pdf.text('Generated by Erasmus Memory Capsule', margin, pageH - 10);

        pdf.save(`note-from-${writerName.replace(' ', '-')}-${id}.pdf`);
      })(),
      {
        loading: 'Generating PDF...',
        success: 'PDF downloaded!',
        error: 'Failed to generate PDF',
      }
    );
  };

  const handleDownloadPhoto = async () => {
    if (!photoCardRef.current) return;
    toast.promise(
      (async () => {
        const canvas = await html2canvas(photoCardRef.current!, {
          scale: 2,
          useCORS: true,
          backgroundColor: null,
        });
        const link = document.createElement('a');
        link.download = `note-card-${id}.png`;
        link.href = canvas.toDataURL('image/png');
        link.click();
      })(),
      {
        loading: 'Creating photo card...',
        success: 'Photo card downloaded!',
        error: 'Failed to create photo card',
      }
    );
  };

  const preview = content.length > 200 ? content.slice(0, 200) + '...' : content;

  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-amber-100 dark:border-slate-700 overflow-hidden">
      <div className="p-5">
        <div className="flex items-start gap-3 mb-3">
          {writerPhotoURL ? (
            <img src={writerPhotoURL} alt={writerName} className="w-12 h-12 rounded-full object-cover flex-shrink-0" />
          ) : (
            <div className="w-12 h-12 rounded-full bg-amber-200 dark:bg-slate-600 flex items-center justify-center text-lg font-bold text-amber-700 dark:text-amber-300 flex-shrink-0">
              {writerName[0]}
            </div>
          )}
          <div className="flex-1 min-w-0">
            <p className="font-semibold text-slate-800 dark:text-white">{writerName}</p>
            <p className="text-xs text-slate-500 dark:text-slate-400">{writerUniversity}</p>
            <p className="text-xs text-amber-600 dark:text-amber-400 mt-0.5">{dateStr}</p>
          </div>
        </div>

        <div className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
          <p className="whitespace-pre-wrap">{expanded ? content : preview}</p>
          {content.length > 200 && (
            <button
              onClick={() => setExpanded(!expanded)}
              className="flex items-center gap-1 mt-2 text-amber-600 dark:text-amber-400 hover:underline text-xs font-medium"
            >
              {expanded ? <><ChevronUp size={14} /> Show less</> : <><ChevronDown size={14} /> Read more</>}
            </button>
          )}
        </div>

        <div className="flex gap-2 mt-4">
          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-amber-200 dark:border-slate-600 text-amber-700 dark:text-amber-300 hover:bg-amber-50 dark:hover:bg-slate-700 text-xs font-medium transition-colors"
          >
            <FileDown size={13} />
            Download PDF
          </button>
          <button
            onClick={handleDownloadPhoto}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-amber-200 dark:border-slate-600 text-amber-700 dark:text-amber-300 hover:bg-amber-50 dark:hover:bg-slate-700 text-xs font-medium transition-colors"
          >
            <Image size={13} />
            Photo Card
          </button>
        </div>
      </div>

      {/* Hidden photo card for html2canvas */}
      <div className="fixed -left-[9999px] -top-[9999px]">
        <div
          ref={photoCardRef}
          style={{ width: 600, padding: 40, background: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 40%, #d97706 100%)', borderRadius: 24, fontFamily: 'Georgia, serif' }}
        >
          <div style={{ marginBottom: 24 }}>
            <p style={{ fontSize: 28, fontWeight: 'bold', color: '#fff', margin: 0 }}>✈️ Memory Capsule</p>
            <p style={{ fontSize: 13, color: 'rgba(255,255,255,0.8)', marginTop: 4 }}>Erasmus Memory Note</p>
          </div>
          <div style={{ background: 'rgba(255,255,255,0.95)', borderRadius: 16, padding: 28 }}>
            <div style={{ marginBottom: 16 }}>
              <p style={{ fontSize: 11, color: '#9ca3af', margin: '0 0 4px 0', textTransform: 'uppercase', letterSpacing: 1 }}>From</p>
              <p style={{ fontSize: 18, fontWeight: 'bold', color: '#1e293b', margin: 0 }}>{writerName}</p>
              <p style={{ fontSize: 13, color: '#64748b', marginTop: 2 }}>{writerUniversity} · {dateStr}</p>
            </div>
            <div style={{ borderTop: '1px solid #fde68a', paddingTop: 16 }}>
              <p style={{ fontSize: 14, color: '#374151', lineHeight: 1.7, margin: 0, whiteSpace: 'pre-wrap' }}>
                {content.length > 400 ? content.slice(0, 400) + '...' : content}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NoteCard;
